version: "2.13.0"
services:
  service1:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - some-mariadb
    command: sh -c './wait-for mysql_db:3306 -- npm start'

  service3:
    build: ../service3/
    depends_on:
      - kafka

  service2:
    build: ../service2/
    depends_on:
      - kafka
#      - service1:
#          condition: service_started
    restart: always

  some-mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - .:/bitnami/mariadb
    environment:
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: example-user
      MYSQL_PASSWORD: my_cool_secret
      MYSQL_ROOT_PASSWORD: my-secret-pw
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT_HOST://:29092,PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
